prompt_order = [
  "directory",
  "git_branch",
  "git_status",
  "jobs",
  "character",
]
add_newline = false

[character]
symbol = "🙈"
vicmd_symbol = "🙉"

[cmd_duration]
prefix = ""

[git_status]
prefix = ""
suffix = " "

[git_branch]
symbol = ""
truncation_length = 10

[directory]
truncation_length = 1
style = "bold white"

[jobs]
symbol = "+"
