prompt_order = [
  "username",
  "hostname",
  "kubernetes",
  "directory",
  "git_branch",
  "git_state",
  "git_status",
  "package",
  "dotnet",
  "golang",
  "java",
  "nodejs",
  "python",
  "ruby",
  "rust",
  "nix_shell",
  "conda",
  "memory_usage",
  "aws",
  "env_var",
  "cmd_duration",
  "line_break",
  "jobs",
  "time",
  "character",
  "battery",
]

add_newline = false

[character]
symbol = "Î»"
vicmd_symbol = "Î›"
# symbol = "ðŸ™ˆ "
# vicmd_symbol = "ðŸ™‰ "

[cmd_duration]
prefix = ""

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[[battery.display]]
threshold = 30
style = "bold red"

[git_status]
prefix = ""
suffix = " "

[directory]
truncation_length = 1
style = "bold white"

[jobs]
symbol = "+"

[nodejs]
symbol = "N "

[python]
symbol = "P "

[env_var]
disabled = true

[aws]
disabled = true

[kubernetes]
disabled = true

[golang]
disabled = true

[conda]
disabled = true

[dotnet]
disabled = true

[line_break]
disabled = true

[package]
disabled = true

[java]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true
